### ISSUE TITLE
As a user I want to see the building labels on the map 

### ISSUE THREAD

**Issue by carlitalabbe** [MinaSelim/SOEN390#61]
<img width="275" alt="Screen Shot 2020-03-06 at 5 18 27 PM" src="https://user-images.githubusercontent.com/22159403/76126965-80618d80-5fce-11ea-9be3-c198fffa7f41.png">

- [ ] create building labels as images for each building

- [ ] find the appropriate coordinates for the position of each building label

- [ ]  add images as ground overlay to the map

**Comment by LouisBenjamin** [comment]
Closed due to time restriction
