### ISSUE TITLE
The search bar relative positions do not work depending on the screen size (< 5.5”) 

### ISSUE THREAD

**Issue by carlitalabbe** [MinaSelim/SOEN390#84]
The search bar relative positions do not work depending on the screen size bigger than 5.5”
![searchbar-bug](https://user-images.githubusercontent.com/22159403/77130895-fda9eb00-6a2f-11ea-801a-dd1ca6483fd2.jpg)

**Comment by FelixDaCat7** [comment]
I solved this bug, will be merged soon.
