### ISSUE TITLE
the default location should be the users current location

### ISSUE THREAD

**Issue by carlitalabbe** [MinaSelim/SOEN390#87]
As of now the default location is the SGW campus and is highlighted in the campus toggle button. Instead, the default location of the app upon opening should be the user's current location.

**Comment by mcalixte** [comment]
![Screenshot_20200407-204056__01](https://user-images.githubusercontent.com/25334458/78735377-aef9bd80-7918-11ea-9e59-ca70ccb270af.jpg)
THis is fixedd in the current, most-recent PR made to address this.
